//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace CircuitCrawlerEditor.Parser {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Level {
        
        private LevelTileset tilesetField;
        
        private LevelEntities entitiesField;
        
        private LevelTriggers triggersField;
        
        private LightInfo[] lightsField;
        
        private LevelTeleporterLinker[] teleporterLinkerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LevelTileset Tileset {
            get {
                return this.tilesetField;
            }
            set {
                this.tilesetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LevelEntities Entities {
            get {
                return this.entitiesField;
            }
            set {
                this.entitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LevelTriggers Triggers {
            get {
                return this.triggersField;
            }
            set {
                this.triggersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Light", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public LightInfo[] Lights {
            get {
                return this.lightsField;
            }
            set {
                this.lightsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TeleporterLinker", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LevelTeleporterLinker[] TeleporterLinker {
            get {
                return this.teleporterLinkerField;
            }
            set {
                this.teleporterLinkerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LevelTileset {
        
        private TileInfo[] tileField;
        
        private string xField;
        
        private string yField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Tile", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TileInfo[] Tile {
            get {
                return this.tileField;
            }
            set {
                this.tileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TileInfo {
        
        private tileStateType stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public tileStateType state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum tileStateType {
        
        /// <remarks/>
        FLOOR,
        
        /// <remarks/>
        WALL,
        
        /// <remarks/>
        PIT,
        
        /// <remarks/>
        SLIP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LightInfo {
        
        private int indexField;
        
        private string ambientField;
        
        private string diffuseField;
        
        private string positionField;
        
        private float constAttenField;
        
        private float linAttenField;
        
        private float quadAttenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ambient {
            get {
                return this.ambientField;
            }
            set {
                this.ambientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string diffuse {
            get {
                return this.diffuseField;
            }
            set {
                this.diffuseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float constAtten {
            get {
                return this.constAttenField;
            }
            set {
                this.constAttenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float linAtten {
            get {
                return this.linAttenField;
            }
            set {
                this.linAttenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float quadAtten {
            get {
                return this.quadAttenField;
            }
            set {
                this.quadAttenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TeleporterInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpikeWallInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PuzzleBoxInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlayerInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BallInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BlockInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoorInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LaserShooterInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CannonInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ButtonInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BreakableDoorInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EntityInfo {
        
        private string idField;
        
        private float xPosField;
        
        private float yPosField;
        
        private float angleField;
        
        private bool angleFieldSpecified;
        
        private float xSclField;
        
        private bool xSclFieldSpecified;
        
        private float ySclField;
        
        private bool ySclFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float xPos {
            get {
                return this.xPosField;
            }
            set {
                this.xPosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float yPos {
            get {
                return this.yPosField;
            }
            set {
                this.yPosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float angle {
            get {
                return this.angleField;
            }
            set {
                this.angleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool angleSpecified {
            get {
                return this.angleFieldSpecified;
            }
            set {
                this.angleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float xScl {
            get {
                return this.xSclField;
            }
            set {
                this.xSclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xSclSpecified {
            get {
                return this.xSclFieldSpecified;
            }
            set {
                this.xSclFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float yScl {
            get {
                return this.ySclField;
            }
            set {
                this.ySclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ySclSpecified {
            get {
                return this.ySclFieldSpecified;
            }
            set {
                this.ySclFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TeleporterInfo : EntityInfo {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SpikeWallInfo : EntityInfo {
        
        private directionType dirField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public directionType dir {
            get {
                return this.dirField;
            }
            set {
                this.dirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum directionType {
        
        /// <remarks/>
        LEFT,
        
        /// <remarks/>
        RIGHT,
        
        /// <remarks/>
        UP,
        
        /// <remarks/>
        DOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PuzzleBoxInfo : EntityInfo {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PlayerInfo : EntityInfo {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BallInfo : EntityInfo {
        
        private float frictionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float friction {
            get {
                return this.frictionField;
            }
            set {
                this.frictionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BlockInfo : EntityInfo {
        
        private float frictionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float friction {
            get {
                return this.frictionField;
            }
            set {
                this.frictionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoorInfo : EntityInfo {
        
        private directionType dirField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public directionType dir {
            get {
                return this.dirField;
            }
            set {
                this.dirField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LaserShooterInfo : EntityInfo {
        
        private float stupidityField;
        
        private float beamWidthField;
        
        private float shotsPerSecondField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float stupidity {
            get {
                return this.stupidityField;
            }
            set {
                this.stupidityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float beamWidth {
            get {
                return this.beamWidthField;
            }
            set {
                this.beamWidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float shotsPerSecond {
            get {
                return this.shotsPerSecondField;
            }
            set {
                this.shotsPerSecondField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CannonInfo : EntityInfo {
        
        private float stupidityField;
        
        private float shotVelocityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float stupidity {
            get {
                return this.stupidityField;
            }
            set {
                this.stupidityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float shotVelocity {
            get {
                return this.shotVelocityField;
            }
            set {
                this.shotVelocityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ButtonInfo : EntityInfo {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BreakableDoorInfo : EntityInfo {
        
        private int maxHitsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int maxHits {
            get {
                return this.maxHitsField;
            }
            set {
                this.maxHitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LevelEntities {
        
        private TeleporterInfo[] teleporterField;
        
        private BreakableDoorInfo[] breakableDoorField;
        
        private ButtonInfo[] buttonField;
        
        private CannonInfo[] cannonField;
        
        private DoorInfo[] doorField;
        
        private BlockInfo[] blockField;
        
        private BallInfo[] ballField;
        
        private PuzzleBoxInfo[] puzzleBoxField;
        
        private SpikeWallInfo[] spikeWallField;
        
        private LaserShooterInfo[] laserShooterField;
        
        private PlayerInfo playerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Teleporter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TeleporterInfo[] Teleporter {
            get {
                return this.teleporterField;
            }
            set {
                this.teleporterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BreakableDoor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BreakableDoorInfo[] BreakableDoor {
            get {
                return this.breakableDoorField;
            }
            set {
                this.breakableDoorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Button", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ButtonInfo[] Button {
            get {
                return this.buttonField;
            }
            set {
                this.buttonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cannon", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CannonInfo[] Cannon {
            get {
                return this.cannonField;
            }
            set {
                this.cannonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Door", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DoorInfo[] Door {
            get {
                return this.doorField;
            }
            set {
                this.doorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Block", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BlockInfo[] Block {
            get {
                return this.blockField;
            }
            set {
                this.blockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ball", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BallInfo[] Ball {
            get {
                return this.ballField;
            }
            set {
                this.ballField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PuzzleBox", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PuzzleBoxInfo[] PuzzleBox {
            get {
                return this.puzzleBoxField;
            }
            set {
                this.puzzleBoxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SpikeWall", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SpikeWallInfo[] SpikeWall {
            get {
                return this.spikeWallField;
            }
            set {
                this.spikeWallField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LaserShooter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LaserShooterInfo[] LaserShooter {
            get {
                return this.laserShooterField;
            }
            set {
                this.laserShooterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PlayerInfo Player {
            get {
                return this.playerField;
            }
            set {
                this.playerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LevelTriggers {
        
        private LevelTriggersCause[] causeField;
        
        private LevelTriggersEffect[] effectField;
        
        private LevelTriggersTrigger[] triggerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cause", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LevelTriggersCause[] Cause {
            get {
                return this.causeField;
            }
            set {
                this.causeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Effect", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LevelTriggersEffect[] Effect {
            get {
                return this.effectField;
            }
            set {
                this.effectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Trigger", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LevelTriggersTrigger[] Trigger {
            get {
                return this.triggerField;
            }
            set {
                this.triggerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LevelTriggersCause {
        
        private string idField;
        
        private causeType typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public causeType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum causeType {
        
        /// <remarks/>
        CauseNOT,
        
        /// <remarks/>
        CauseOR,
        
        /// <remarks/>
        CauseAND,
        
        /// <remarks/>
        CauseXOR,
        
        /// <remarks/>
        CauseButton,
        
        /// <remarks/>
        CauseEntityDestruction,
        
        /// <remarks/>
        CauseLocation,
        
        /// <remarks/>
        CauseOffScreen,
        
        /// <remarks/>
        CauseTimePassed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LevelTriggersEffect {
        
        private string idField;
        
        private effectType typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public effectType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum effectType {
        
        /// <remarks/>
        EffectActivateNodeLink,
        
        /// <remarks/>
        EffectAND,
        
        /// <remarks/>
        EffectDeactivateNodeLink,
        
        /// <remarks/>
        EffectDoor,
        
        /// <remarks/>
        EffectEndGame,
        
        /// <remarks/>
        EffectList,
        
        /// <remarks/>
        EffectRaiseBridge,
        
        /// <remarks/>
        EffectRemoveEntity,
        
        /// <remarks/>
        EffectTriggerTimer,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LevelTriggersTrigger {
        
        private string causeField;
        
        private string effectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cause {
            get {
                return this.causeField;
            }
            set {
                this.causeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string effect {
            get {
                return this.effectField;
            }
            set {
                this.effectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LevelTeleporterLinker {
        
        private string t1Field;
        
        private string t2Field;
        
        private bool oneWayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string t1 {
            get {
                return this.t1Field;
            }
            set {
                this.t1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string t2 {
            get {
                return this.t2Field;
            }
            set {
                this.t2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool oneWay {
            get {
                return this.oneWayField;
            }
            set {
                this.oneWayField = value;
            }
        }
    }
}
